### ISSUE TITLE
Tag with DNSDist Version

### ISSUE THREAD

**Issue by hmajid2301** [tcely/dockerhub-powerdns#11]
Hey,

This is really cool project, would it be possible to tag the Docker releases with the version of the software it is running. For example I need to use DoH in DNSDist and need to use a specific version of DNSDist. So I could pull say `docker pull tcely/dnsdist:1.5.0-rc1`.

Using the changelog versions: https://dnsdist.org/changelog.html.

Thanks.

**Comment by tcely** [comment]
A scheme like this would involve more manual work to keep it useful than I'm willing to invest.

A specific build is easy to run:
```
dnsdistvb () {
    for _version in "$@"; do
        docker build \
            --build-arg "DNSDIST_VERSION=$_version" \
            --force-rm --pull -t "tcely/dnsdist:$_version" \
            'https://github.com/tcely/dockerhub-powerdns.git#master:dnsdist'
    done
    unset -v _version
}

dnsdistvb '1.5.0-rc1'

```

I started this up and will push the tag when it finishes.
