### ISSUE TITLE
Missing DoH feature

### ISSUE THREAD

**Issue by ginnyTheCat** [tcely/dockerhub-powerdns#13]
If I run `docker run -it tcely/dnsdist:1.5.0-rc1 --version` only DNS-over-TLS shows up. No DNS-over-HTTPS support. This is also in the `:latest` tag the case.

Running a container with a config that used DoH exits with an error:
`Caught exception: addDOHLocal() called but DNS over HTTPS support is not present!`

It would be really nice if you could add this.

**Comment by tcely** [comment]
Try the aports tag instead. I have no plans for adding this, but I noticed the aport already did.
