### ISSUE TITLE
Update for docker images

### ISSUE THREAD

**Issue by d-bourdon** [tcely/dockerhub-powerdns#14]
Hello,

I was wondering if it was possible to update the current images on docker image, particularly for powerdns-recursor (But I guess the other images too).

The actual version of PowerDNS  Recursor shipped inside the container is 1.3.1. (checked after fresh pull) but PowerDNS have release an advisory about a CVE : [PowerDns advisory](https://doc.powerdns.com/recursor/security-advisories/powerdns-advisory-2020-04.html)

Thank you ;)

**Comment by tcely** [comment]
I'm getting to this currently. You'll have better luck reaching me over at Twitter for this kind of thing.

I'm happy to kick off builds but often I find Alpine broke something (e.g. man disappeared) so it may take a while.
