### ISSUE TITLE
Question: Build 

### ISSUE THREAD

**Issue by Berndinox** [tcely/dockerhub-powerdns#20]
Hy! Why not just doing:

`RUN apk --update --no-cache add pdns`

Instead of the manual build?
Just curious…

**Comment by tcely** [comment]
Building from source is the purpose of this image.

For the package image, see:

-  ([Dockerfile](https://github.com/tcely/dockerhub-powerdns/blob/aports/authoritative/Dockerfile)) https://hub.docker.com/layers/tcely/powerdns-server/aports/images/sha256-695a2bb85b1652ad8ba63f9ddf363f48ad387789ea0425f46f3c47ae480bc5d3?context=explore
-  ([Dockerfile](https://github.com/tcely/dockerhub-alpine/blob/master/pdns/Dockerfile)) https://hub.docker.com/layers/tcely/alpine-aports/pdns/images/sha256-a7710dee3aea7479c03f43990017e841b7ffcdcf41737df202b4ca1fb663d13d?context=explore
