### ISSUE TITLE
Add support for geoip backend

### ISSUE THREAD

**Issue by blop** [tcely/dockerhub-powerdns#5]
Hello,

Could you include the geoip backend module in your build as well ?

It can be added to the  --with-dynmodules list (geoip) and only requires those extra apk packages : 
```
geoip-dev yaml-cpp-dev (for building)
geoip yaml-cpp (for running)
```

Thanks!

**Comment by tcely** [comment]
The `aports` tag should be updated and ready for use now. The `latest` tag is currently building.
