### ISSUE TITLE
How do you configure dnsdist to use the recursor container? 

### ISSUE THREAD

**Issue by dokbua** [tcely/dockerhub-powerdns#6]
Not an issue per-se, but a question:

dnsdist.conf requires the resolver to be added by IP address, like

> `newServer{address='192.168.1.1:5300', order=2}`

 and the IP address is randomly assigned by docker on docker-start.   I tried using the servers IP address, but that also does not work, as the resolver replies through the internal address causing confusion for dnsdist.

**Comment by tcely** [comment]
I personally use statically assigned addresses.

**Comment by dokbua** [comment]
How do you do that? Inside the container?  
Sorry but I'm really stuck with this problem!

**Comment by tcely** [comment]
See https://blog.alejandrocelaya.com/2017/04/21/set-specific-ip-addresses-to-docker-containers-created-with-docker-compose/
