### ISSUE TITLE
Container exited with code 0

### ISSUE THREAD

**Issue by lehha** [tcely/dockerhub-powerdns#9]
dnsdist in 1.4.0 goes to background, and Docker stop container.

I've change CMD in Dockerfile:
`CMD ["--supervised", "--disable-syslog"]`

and it's run correctly in foreground.

Can you fix in REAMDE.md?

**Comment by tcely** [comment]
Is the change in #10 what you meant?

**Comment by lehha** [comment]
Yes, this correct!
